trainer: default

dataset_path: './singlecoil'
logs_dir: './logs'

epochs: 50
batch_size: 32

model__entity_kwargs:
  entity: stylishfastmri
  kwargs: {
    z_encoder_kwargs: {},
    w_encoder_kwargs: {}, 
    base_model_kwargs: { block_kwargs_list: [{
      num_classes: 2,
      min_channels: 32,
      max_channels: 512,
      num_down_blocks: 4,
      use_texture_injection: True,
      texture_dim: 320,
      use_noise_injection: True
    }]}
  }
model__optimizer_entity_kwargs:
  entity: 'adam'
  kwargs: {lr: 0.0002}
model__scheduler_entity_kwargs: null
# model__scheduler_entity_kwargs:
#   entity: lambdalr
#   kwargs: {base: 0.96}

discriminator__entity_kwargs: 
  entity: discriminator
  kwargs: {in_channels: 1, inter_channels: [64, 128, 256, 512]}
discriminator__optimizer_entity_kwargs:
  entity: 'adam'
  kwargs: {lr: 0.0002, betas: [0., 0.999]}
discriminator__scheduler_entity_kwargs: null

texture_proxy__entity_kwargs:
  entity: mobilenet_v2_encoder
  kwargs: {}

criterion__entity2_kwargs_list: [
  { entity: ['rec', 'l1'], kwargs: {} },
  { entity: ['kl_normal', 'kl_normal'], kwargs: {} },
  { entity: ['texture', 'l1'], kwargs: {} },
  { entity: ['adv', 'non_saturating_gan'], kwargs: { coef: 0.001 } },
]
