trainer: default_base

dataset_path: './singlecoil'
logs_dir: './logs'

epochs: 50
batch_size: 8

model__entity_kwargs:
  entity: basestylishfastmri
  kwargs: {
      num_classes: 2,
      min_channels: 32,
      max_channels: 512,
      num_down_blocks: 4,
      use_texture_injection: False,
      use_noise_injection: False
  }
model__optimizer_entity_kwargs:
  entity: 'adam'
  kwargs: {lr: 0.0002}
model__scheduler_entity_kwargs: null

discriminator__entity_kwargs: 
  entity: discriminator
  kwargs: {in_channels: 1, inter_channels: [64, 128, 256, 512]}
discriminator__optimizer_entity_kwargs:
  entity: 'adam'
  kwargs: {lr: 0.0002, betas: [0., 0.999]}
discriminator__scheduler_entity_kwargs: null

criterion__entity2_kwargs_list: [
  { entity: ['rec', 'l1'], kwargs: {} },
  { entity: ['adv', 'non_saturating_gan'], kwargs: { coef: 0.01 } },
]
